/**
 * Generated by MicroLang
 */
package microservices.proxy;

import microservices.CatService;
import lib.HttpUtil;
import java.io.IOException;

public class CatServiceProxy implements CatService {
	
	private HttpUtil util = new HttpUtil();
	
	@Override
	public int postCat(int catYears) {
		try {
			String response = util.sendRequest("http://" + HOST + ":" + PORT + "/cat", "POST", "catYears=" + catYears + "");
			return Integer.valueOf(response);
		}
		catch (IOException e) {
			e.printStackTrace();
		}
		return 0;
	}
	
	@Override
	public String getCat() {
		try {
			String response = util.sendRequest("http://" + HOST + ":" + PORT + "/cat", "GET", "");
			return String.valueOf(response);
		}
		catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
	
}
