/**
 * Generated by MicroLang
 */
package microservices.proxy;

import microservices.DogService;
import lib.HttpUtil;
import java.io.IOException;

public class DogServiceProxy implements DogService {
	
	private HttpUtil util = new HttpUtil();
	
	@Override
	public int putDog(int dogYears) {
		try {
			String response = util.sendRequest("http://" + HOST + ":" + PORT + "/dog", "PUT", "dogYears=" + dogYears + "");
			return Integer.valueOf(response);
		}
		catch (IOException e) {
			e.printStackTrace();
		}
		return 0;
	}
	
	@Override
	public String getDog() {
		try {
			String response = util.sendRequest("http://" + HOST + ":" + PORT + "/dog", "GET", "");
			return String.valueOf(response);
		}
		catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
	
	@Override
	public int getDog(double legs) {
		try {
			String response = util.sendRequest("http://" + HOST + ":" + PORT + "/dog/" + legs + "", "GET", "");
			return Integer.valueOf(response);
		}
		catch (IOException e) {
			e.printStackTrace();
		}
		return 0;
	}
	
}
