/**
 * Generated by MicroLang
 */
package impl;

import microservices.abstr.AbstractCatService;

public class CatServiceImpl extends AbstractCatService {
	
	@Override
	public int postCat(int catYears) {
		//TODO: implement endpoint logic here
		return 0;
	}
	
	@Override
	public String getCat() {
		//TODO: implement endpoint logic here
		return null;
	}
	
	public static void main(String[] args) {
		new CatServiceImpl().run();
	}

}
