/**
 * Generated by MicroLang
 */
package impl;

import microservices.abstr.AbstractDogService;

public class DogServiceImpl extends AbstractDogService {
	
	@Override
	public int putDog(int dogYears) {
		//TODO: implement endpoint logic here
		return 0;
	}
	
	@Override
	public String getDog() {
		//TODO: implement endpoint logic here
		return null;
	}
	
	@Override
	public int getDog(double legs) {
		//TODO: implement endpoint logic here
		return 0;
	}
	
	public static void main(String[] args) {
		new DogServiceImpl().run();
	}

}
