/**
 * Generated by MicroLang
 */
package impl;

import microservices.abstr.AbstractPetStoreService;

public class PetStoreServiceImpl extends AbstractPetStoreService {
	
	@Override
	public String getPet(String type) {
		//TODO: implement endpoint logic here
		return null;
	}
	
	@Override
	public int postPet(String type, String name, String description) {
		//TODO: implement endpoint logic here
		return 0;
	}
	
	public static void main(String[] args) {
		new PetStoreServiceImpl().run();
	}

}
