/**
 * Generated by MicroLang
 */
package microservices.abstr;

import microservices.DogService;
import lib.HttpUtil;
import java.util.Map;
import java.util.HashMap;
import java.io.IOException;
import java.net.InetSocketAddress;
import com.sun.net.httpserver.HttpServer;

public abstract class AbstractDogService implements DogService, Runnable {
	
	protected HttpUtil util = new HttpUtil();
	
	@Override
	public final void run() {
		try {
			HttpServer server = HttpServer.create(new InetSocketAddress(PORT), 0);
			server.createContext("/", exchange -> {
				String path = exchange.getRequestURI().getPath();
				String method = exchange.getRequestMethod();
				System.out.println(method + " " + path);
				String body = util.getBody(exchange.getRequestBody());
				System.out.println("body: " + body);
				Map<String, String> parameters = new HashMap<>();
				try {
					parameters = util.toMap(body);
				}
				catch (Exception e) {
					util.sendResponse(exchange, 400, "Malformed parameters in body");
					return;
				}
				System.out.println("parameters: " + parameters);
				if (path.matches("\\/dog")) {
					System.out.println("/dog was hit");
					switch (method) {
						case "PUT": {
							int dogYears = Integer.valueOf(parameters.get("dogYears"));
							Object response = putDog(dogYears);
							util.sendResponse(exchange, 200, response);
							return;
						}
						default:
							util.sendResponse(exchange, 405, method + " is not implemented on " + path);
					}
				}
				if (path.matches("\\/dog")) {
					System.out.println("/dog was hit");
					switch (method) {
						case "GET": {
							Object response = getDog();
							util.sendResponse(exchange, 200, response);
							return;
						}
						default:
							util.sendResponse(exchange, 405, method + " is not implemented on " + path);
					}
				}
				if (path.matches("\\/dog\\/[0-9]+(\\.[0-9]+)")) {
					System.out.println("/dog/{double} was hit");
					switch (method) {
						case "GET": {
							double legs = Double.valueOf(path.split("/")[2]);
							Object response = getDog(legs);
							util.sendResponse(exchange, 200, response);
							return;
						}
						default:
							util.sendResponse(exchange, 405, method + " is not implemented on " + path);
					}
				}
				else {
					util.sendResponse(exchange, 404, path + " could not be found");
				}
			});
			server.start();
			System.out.println("Now listening on port " + PORT);
		}
		catch (IOException e) {
			e.printStackTrace();
		}
	}

}
