/**
 * Generated by MicroLang
 */
package microservices.abstr;

import microservices.PetStoreService;
import microservices.DogService;
import microservices.proxy.DogServiceProxy;
import microservices.CatService;
import microservices.proxy.CatServiceProxy;
import lib.HttpUtil;
import java.util.Map;
import java.util.HashMap;
import java.io.IOException;
import java.net.InetSocketAddress;
import com.sun.net.httpserver.HttpServer;

public abstract class AbstractPetStoreService implements PetStoreService, Runnable {
	
	protected HttpUtil util = new HttpUtil();
	protected DogService dogService = new DogServiceProxy();
	protected CatService catService = new CatServiceProxy();
	
	@Override
	public final void run() {
		try {
			HttpServer server = HttpServer.create(new InetSocketAddress(PORT), 0);
			server.createContext("/", exchange -> {
				String path = exchange.getRequestURI().getPath();
				String method = exchange.getRequestMethod();
				System.out.println(method + " " + path);
				String body = util.getBody(exchange.getRequestBody());
				System.out.println("body: " + body);
				Map<String, String> parameters = new HashMap<>();
				try {
					parameters = util.toMap(body);
				}
				catch (Exception e) {
					util.sendResponse(exchange, 400, "Malformed parameters in body");
					return;
				}
				System.out.println("parameters: " + parameters);
				if (path.matches("\\/pet\\/(?!(true|false)\\b)\\b\\w+")) {
					System.out.println("/pet/{string} was hit");
					switch (method) {
						case "GET": {
							String type = String.valueOf(path.split("/")[2]);
							Object response = getPet(type);
							util.sendResponse(exchange, 200, response);
							return;
						}
						case "POST": {
							String type = String.valueOf(path.split("/")[2]);
							String name = String.valueOf(parameters.get("name"));
							String description = String.valueOf(parameters.get("description"));
							Object response = postPet(type, name, description);
							util.sendResponse(exchange, 200, response);
							return;
						}
						default:
							util.sendResponse(exchange, 405, method + " is not implemented on " + path);
					}
				}
				else {
					util.sendResponse(exchange, 404, path + " could not be found");
				}
			});
			server.start();
			System.out.println("Now listening on port " + PORT);
		}
		catch (IOException e) {
			e.printStackTrace();
		}
	}

}
