/**
 * Generated by MicroLang
 */
package microservices;

public interface CatService {
	
	String HOST = "192.168.0.3";
	int PORT = 5002;
	
	int postCat(int catYears);
	
	String getCat();
	
	int getCat(double legs);
	
}
