/**
 * Generated by MicroLang
 */
package microservices;

public interface PetStoreService {
	
	String HOST = "192.168.0.1";
	int PORT = 5000;
	
	String getPet(String type);
	
	int postPet(String type, String name, String description);
	
}
